---
title: "Accidentes de tráfico y leyes de circulación (I)"
author: "EC1027 --- Econometría I"
date: "Curso 2021-2022"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Planteamiento

El archivo de Excel `traffic2.xlsx` contiene 108 observaciones mensuales que cubren el periodo que va desde enero de 1981 hasta diciembre de 1989 y recoge información sobre accidentes automovilísticos en California, leyes de tráfico y algunas otras variables relacionadas. Utilice ese conjunto de datos para responder a las siguientes cuestiones:

1. La variable ficticia $\textit{beltlaw}$ toma el valor 1 en los meses posteriores a la introducción de una ley  que hacía obligatorio el uso del cinturón de seguridad en California. ¿En qué mes y año entró en vigor esta ley? La variable ficticia $\textit{spdlaw}$ toma el valor 1 a partir de la entrada en vigor de una ley que elevaba el límite de velocidad desde 50 millas por hora hasta 65 millas por hora. ¿Cuando se elevó el límite de velocidad?

2. Cree una nueva variable, $\textit{ltotacc}$ que sea igual al logaritmo del número de accidentes totales, $\textit{totacc}$. Represente gráficamente la evolución de $\textit{ltotacc}$ a lo largo del periodo muestral. Regrese la variable $\textit{ltotacc}$ sobre una tendencia lineal y variables ficticias mensuales. Interprete el coeficiente estimado de la tendencia. ¿Qué significan los parámetros de las ficticias estacionales? ¿Son conjuntamente significativas las variaciones estacionales?

3. Amplíe la  la regresión del apartado anterior incluyendo como explicativas las variables $\textit{wkends}$ (número de días de fin de semana en cada mes), $\textit{unem}$ (tasa de desempleo), $\textit{spdlaw}$ (ley que eleva el límite de velocidad) y $\textit{beltlaw}$ (ley que hace obligatorio el uso del cinturón de seguridad). Interprete el coeficiente de la variable $\textit{unem}$: ¿tiene sentido el signo de dicho coeficiente?

4. Interprete la estimaciones de los parámetros de las variables $\textit{spdlaw}$ y $\textit{beltlaw}$ en la regresión del apartado anterior. ¿Coinciden los efectos estimados de estas variables con los esperados? Explique su respuesta.

5. La variable $\textit{fatacc}$ representa el número de accidentes en los que se ha producido al menos un fallecimiento. Construya una nueva variable, $\textit{prcfat}$, calculando el porcentaje que representan los accidentes fatales sobre el total de accidentes. Represente gráficamente la evolución temporal de la variable $\textit{prcfat}$. Estime los parámetros de un modelo de regresión con $\textit{prcfat}$ como variable dependiente y con las mismas variables explicativas que en el modelo de regresión del punto 3. Comente los efectos estimados y la significación de las variables ficticias que captan los efectos de la ley que regula el límite de velocidad y de la ley que hace obligatorio el uso del cinturón de seguridad.

