project:
  title: "labs_1027"
  output-dir: html
  render:
    - "01 - intro/*.qmd"
    - "02 - vote1/*.qmd"
    - "03 - bwght/*.qmd"
    - "04 - hprice1/*.qmd"
    - "05 - econmath/*.qmd"
    - "06 - smoke/*.qmd"
    - "07 - loanapp/*.qmd"
    - "08 - wagegap/*.qmd"
    - "09 - engel/*.qmd"
    - "10 - outliers/*.qmd"

author: "José Pernías"
date: last-modified
lang: es
toc-title: Contenido
toc: true
number-sections: true
number-depth: 3
format-links: false

format:
  html:
    theme:
      - flatly
      - labs_1027.scss
    embed-resources: true


