---
title: "La ley de Okun en España: 1980--2019"
author: "EC1027 --- Econometría I"
date: "Curso 2022-2023"
bibliography: okun.bib
link-citations: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```


# Instrucciones {.unnumbered}

1. Descargue el archivo `okun.zip` y descomprímalo. Este archivo contiene una carpeta `okun` donde se encuentran varios documentos:
    - `okun.csv`: datos en formato csv.

    - `okun_templ.R`: plantilla que debe completar para realizar la tarea.

    - `okun.Rproj`: opciones de proyecto de RStudio.

    - `okun-instr.html`: este documento.

2. Haga una copia de `okun_templ.R` y guárdela con el nombre `okun.R` dentro de la carpeta `okun`. Utilice el documento `okun.R` para completar la tarea y no modifique `okun_templ.R` que servirá como copia de seguridad.

3. Para trabajar en el proyecto haga doble-click sobre el icono de `okun.Rproj`. Alternativamente, abra el proyecto desde RStudio usando el menú `File | Open Project...` y seleccione el archivo `okun.Rproj`.

4. **No olvide escribir su nombre completo al principio de `okun.R`**.

5. Para llevar a cabo la tarea que se describe en este documento complete el archivo `okun.R` siguiendo las instrucciones que aparecen allí. Reemplace con sus respuestas las líneas que contienen los caracteres `## >>>>>>>>>>>>>>>>>>>>>`.

6. Obtenga un documento `okun.html` compilando `okun.R` usando el icono correspondiente en el panel de edición o mediante el menú `File | Compile Report...`.

7. Para entregar su trabajo en el Aula Virtual cree un archivo zip comprimiendo la carpeta `okun` y todos los documentos que contenga. Los archivos zip pueden usarse también para guardar su trabajo y continuarlo en otro ordenador.

8. **Para que la entrega sea considerada válida el archivo zip que se suba al Aula Virtual debe contener, además de los documentos enumerados en el punto 1, los documentos `okun.R`  y `okun.html`, obtenidos como se ha descrito en los puntos 4 a 6.** 


# La ley de Okun

Arthur Okun encontró en 1962 una regularidad empírica entre el desempleo y el nivel de producción agregado. Más recientemente, @ballOkunLawFit2017 estiman diversas especificaciones de la ley de Okun para varios países en el periodo 1980--2013. Las estimaciones que obtuvieron estos autores para España indicarían que un incremento de la producción de un $1\%$ reduciría la tasa de desempleo entre 0.7 y 0.9 puntos porcentuales. En este laboratorio trataremos de replicar esos resultados extendiendo el periodo analizado hasta el cuarto trimestre de 2019.

La ley de Okun establece que existe una relación inversa entre el desempleo cíclico y la brecha de la producción:
$$
  u_t - u^n_t = \beta (\log y_t - \log y^p_t) + \epsilon_t, \tag{1}
$$
donde $u_t$ es la tasa de desempleo, $u^n_t$ es la tasa de desempleo natural, $y_t$ es la producción agregada en términos reales e $y^p_t$ es la producción potencial, $\beta$ es un parámetro negativo y $\epsilon_t$ es un término de error que recogería otros factores que afectarían al desempleo cíclico.

Para estimar la ley de Okun se utilizan dos enfoques. La *versión en niveles* de la ley de Okun se obtiene planteando un modelo de regresión similar a la ecuación anterior, lo que requiere obtener aproximaciones de la tasa natural de desempleo y de la producción potencial. Por un lado, obtenemos una aproximación a $u^n_t$ usando el filtro de Hodrick y Prescott sobre la tasa de desempleo, $u_t$. Definimos el empleo cíclico como:
$$
  u^c_t = u_t - u^n_t. \tag{2}
$$
Por otro lado, calculamos la brecha de la producción (*output gap*) como:
$$
  y^b_t = 100  (\log y_t - \log y^p_t), \tag{3}
$$
y aproximamos el logaritmo de la producción potencial con el filtro de Hodrick y Prescott sobre $\log y_t$. Estimaremos la versión en niveles de la ley de Okun con el modelo de retardos distribuidos:
$$
  u^c_t = 
  \alpha_0 + 
  \beta_0 y^b_t + 
  \beta_1 y^b_{t-1} + 
  \dots +
  \beta_L y^b_{t-L} + \epsilon_t.
  \tag{Mod1}
$$
Los parámetros $\beta_0, \beta_1, \dots, \beta_L$ son los multiplicadores dinámicos. En concreto, $\beta_0$ es el multiplicador de corto plazo. También tiene especial interés el multiplicador de largo plazo:
$$
  \beta_{\text{LP}} = \sum_{j = 0}^L \beta_j.
$$

Un segundo enfoque consiste en estimar la *versión en variaciones* de la ley de Okun. Se puede deducir de la ecuación $(1)$ tomando diferencias si se suponen que tanto la tasa natural de desempleo como la producción potencial son constantes en el tiempo. Definiendo la tasa de crecimiento de la producción real como:
$$
 gy_t = 100 \Delta \log y_t,
$$
estimaremos la versión en variaciones con el siguiente modelo de retardos distribuidos:
$$
\Delta u_t = 
\alpha_0 + 
\theta_0 gy_t + 
\theta_1 gy_{t-1} + 
\dots + 
\theta_L gy_{t-L} +
\epsilon_t
,
\tag{Mod2}
$$
En este caso el multiplicador de corto plazo es $\theta_0$ y el multiplicador de largo plazo es:
$$
  \theta_{\text{LP}} = \sum_{j = 0}^L \theta_j.
$$



# Datos

Las dos versiones de la ley de Okun se estimarán con los datos contenidos en el fichero `okun.csv`. Las  variables de ese fichero tienen frecuencia trimestral y cubren el periodo que va desde el segundo trimestre de 1980 hasta el último trimestre de 2019. 

La producción agregada real, `y`, es el PIB a precios constantes (base 2015). Tanto esta variable como la tasa de desempleo, `u`, se han obtenido de la base de datos [BDREMS](https://www.sepg.pap.hacienda.gob.es/sitios/sepg/es-ES/Presupuestos/DocumentacionEstadisticas/Documentacion/paginas/basedatosmodelorems.aspx) (actualización de diciembre de 2021) que proporciona series trimestrales para la economía española que han sido corregidas de estacionalidad y efectos calendario.

Además de la producción agregada y la tasa de desempleo, en el archivo `okun.csv` se proporcionan algunas variables más, las cuales han sido obtenidas a partir de `y` y `u`:

- `ly` y `gy` son, respectivamente, el logaritmo y la tasa de crecimiento de la producción real.

- `un` es la tasa de desempleo natural. Se obtiene aplicando el [filtro de Hodrick y Prescott](https://es.wikipedia.org/wiki/Filtro_de_Hodrick-Prescott) a la tasa de desempleo `u` (en el cálculo se utiliza un parámetro de suavizado $\lambda = 1600$).

- `lyp`es el logaritmo de la producción potencial. Es el filtro de Hodrick y Prescott aplicado al logaritmo de la producción agregada `ly` ($\lambda = 1600$).


# Referencias {-}
